alter table lolik_web.albom drop foreign key FK5897DB51DF1B685;
alter table lolik_web.fotografia drop foreign key FK57027D6CB7C9B96A;
alter table lolik_web.fotografia_ocenka drop foreign key FK4D2265C6C58DAC6A;
alter table lolik_web.fotografia_ocenka drop foreign key FK4D2265C66A89BF0A;
alter table lolik_web.kompozicia drop foreign key FK884ACCE4D226B4CB;
alter table lolik_web.kompozicia_ocenka drop foreign key FKC9403F4E6A89BF0A;
alter table lolik_web.kompozicia_ocenka drop foreign key FKC9403F4E4ADD96A;
alter table lolik_web.lolik_web drop foreign key FKA1DFEF40BDBA5AB9;
alter table lolik_web.lolik_web_ocenka drop foreign key FKEAECFD72136DC95A;
alter table lolik_web.lolik_web_ocenka drop foreign key FKEAECFD726A89BF0A;
alter table lolik_web.muzikalnii_albom drop foreign key FKEF8DA385B9EE77E;
alter table lolik_web.muzikalnii_albom_tranzakcia drop foreign key FKC7802BFC5B403CAA;
alter table lolik_web.muzikalnii_albom_tranzakcia drop foreign key FKC7802BFCD226B4CB;
alter table lolik_web.ocenka drop foreign key FKC30C97934AD111BF;
alter table lolik_web.opros drop foreign key FK650D455136DC95A;
alter table lolik_web.opros_ocenka drop foreign key FK9B1926BD55CAB56A;
alter table lolik_web.opros_ocenka drop foreign key FK9B1926BD6A89BF0A;
alter table lolik_web.polzovatel_otvet drop foreign key FK45A458AF55CAB56A;
alter table lolik_web.polzovatel_otvet_vopros drop foreign key FKB552FF2FE8EA4A2D;
alter table lolik_web.polzovatel_otvet_vopros drop foreign key FKB552FF2FB08F738A;
alter table lolik_web.razdel drop foreign key FKC8185800DC555A74;
alter table lolik_web.razdel drop foreign key FKC8185800136DC95A;
alter table lolik_web.razdel_fotografii drop foreign key FK61A17B132D9258F1;
alter table lolik_web.razdel_muzika drop foreign key FK366EAB8C2D9258F1;
alter table lolik_web.razdel_ocenka drop foreign key FK38D13CB26A89BF0A;
alter table lolik_web.razdel_ocenka drop foreign key FK38D13CB22D9258F1;
alter table lolik_web.razdel_video drop foreign key FK2342CF7C2D9258F1;
alter table lolik_web.tranzakcia drop foreign key FKA4B86F022914FE30;
alter table lolik_web.video_klip drop foreign key FK9F8D7F8CFFE4F6EC;
alter table lolik_web.video_klip_ocenka drop foreign key FK20B6BFA660CD07E1;
alter table lolik_web.video_klip_ocenka drop foreign key FK20B6BFA66A89BF0A;
alter table lolik_web.vopros drop foreign key FKCFACAD9F55CAB56A;
drop table if exists lolik_web.albom;
drop table if exists lolik_web.fotografia;
drop table if exists lolik_web.fotografia_ocenka;
drop table if exists lolik_web.kompozicia;
drop table if exists lolik_web.kompozicia_ocenka;
drop table if exists lolik_web.lolik_web;
drop table if exists lolik_web.lolik_web_ocenka;
drop table if exists lolik_web.muzikalnii_albom;
drop table if exists lolik_web.muzikalnii_albom_tranzakcia;
drop table if exists lolik_web.ocenka;
drop table if exists lolik_web.opros;
drop table if exists lolik_web.opros_ocenka;
drop table if exists lolik_web.parametr_sistemi;
drop table if exists lolik_web.polzovatel_otvet;
drop table if exists lolik_web.polzovatel_otvet_vopros;
drop table if exists lolik_web.razdel;
drop table if exists lolik_web.razdel_fotografii;
drop table if exists lolik_web.razdel_muzika;
drop table if exists lolik_web.razdel_ocenka;
drop table if exists lolik_web.razdel_video;
drop table if exists lolik_web.tip_razdela;
drop table if exists lolik_web.tranzakcia;
drop table if exists lolik_web.tranzakcia_sostoianie;
drop table if exists lolik_web.video_klip;
drop table if exists lolik_web.video_klip_ocenka;
drop table if exists lolik_web.vopros;
drop table if exists lolik_web.yazik;
drop table if exists lolik_web.znachenie;
create table lolik_web.albom (albom_id integer not null auto_increment, nazvanie varchar(255), opisanie varchar(255), ssilka varchar(255), razdel_kod integer, primary key (albom_id));
create table lolik_web.fotografia (fotografia_id integer not null auto_increment, aktivnaia bit, opisanie varchar(255), ssilka varchar(255), ssilka_malenkaia varchar(255), albom_id integer, primary key (fotografia_id));
create table lolik_web.fotografia_ocenka (ocenka_id integer not null, fotografia_id integer, primary key (ocenka_id));
create table lolik_web.kompozicia (kompozicia_id integer not null auto_increment, kompozitor varchar(255), nazvanie varchar(255), prodolzhitelnost varchar(255), proizvedenie varchar(255), muzikalnii_albom_id integer, primary key (kompozicia_id));
create table lolik_web.kompozicia_ocenka (ocenka_id integer not null, kompozicia_id integer, primary key (ocenka_id));
create table lolik_web.lolik_web (lolik_web_kod integer not null, opisanie varchar(255), yazik_kod varchar(2), primary key (lolik_web_kod));
create table lolik_web.lolik_web_ocenka (ocenka_id integer not null, lolik_web_kod integer, primary key (ocenka_id));
create table lolik_web.muzikalnii_albom (muzikalnii_albom_id integer not null auto_increment, cena decimal(19,2), data_vipuska datetime, format varchar(255), gruppa varchar(255), integranti varchar(255), nazvanie varchar(255), opisanie varchar(255), razmer double precision, ssilka_fail varchar(255), ssilka_oblozhka varchar(255), ssilka_oblozhka_malenkaia varchar(255), razdel_kod integer, primary key (muzikalnii_albom_id));
create table lolik_web.muzikalnii_albom_tranzakcia (kolichestvo_zagruzok integer, tranzakcia_id integer not null, muzikalnii_albom_id integer, primary key (tranzakcia_id));
create table lolik_web.ocenka (ocenka_id integer not null auto_increment, chislo datetime, ip_adres varchar(255), znachenie_kod integer, primary key (ocenka_id));
create table lolik_web.opros (opros_id integer not null auto_increment, aktivnii bit, konec datetime, mono_otvet bit, nachalo datetime, opisanie varchar(255), lolik_web_kod integer, primary key (opros_id));
create table lolik_web.opros_ocenka (ocenka_id integer not null, opros_id integer, primary key (ocenka_id));
create table lolik_web.parametr_sistemi (parametr_sistemi_id integer not null auto_increment, kluch varchar(255), opisanie varchar(255), znachenie varchar(255), primary key (parametr_sistemi_id));
create table lolik_web.polzovatel_otvet (polzovatel_otvet_id integer not null auto_increment, chislo datetime, ip_adres varchar(255), opros_id integer, primary key (polzovatel_otvet_id));
create table lolik_web.polzovatel_otvet_vopros (polzovatel_otvet_id integer not null, vopros_id integer not null, unique (polzovatel_otvet_id, vopros_id));
create table lolik_web.razdel (razdel_kod integer not null, opisanie varchar(255), tip_razdela_kod integer, lolik_web_kod integer, primary key (razdel_kod));
create table lolik_web.razdel_fotografii (razdel_kod integer not null, primary key (razdel_kod));
create table lolik_web.razdel_muzika (razdel_kod integer not null, primary key (razdel_kod));
create table lolik_web.razdel_ocenka (ocenka_id integer not null, razdel_kod integer, primary key (ocenka_id));
create table lolik_web.razdel_video (razdel_kod integer not null, primary key (razdel_kod));
create table lolik_web.tip_razdela (tip_razdela_kod integer not null, nazvanie varchar(255), primary key (tip_razdela_kod));
create table lolik_web.tranzakcia (tranzakcia_id integer not null auto_increment, chislo datetime, ip_adres varchar(255), kluch varchar(255), pokupatel_email varchar(255), pokupatel_familia varchar(255), pokupatel_id varchar(255), pokupatel_imia varchar(255), pokupatel_strana varchar(255), soobshenie varchar(255), stoimost_tovara decimal(19,2), stoimost_tranzakcii decimal(19,2), tranzakcia varchar(255), valuta varchar(255), tranzakcia_sostoianie_kod integer, primary key (tranzakcia_id));
create table lolik_web.tranzakcia_sostoianie (tranzakcia_sostoianie_kod integer not null, opisanie varchar(255), primary key (tranzakcia_sostoianie_kod));
create table lolik_web.video_klip (video_klip_id integer not null auto_increment, aktivnii bit, nazvanie varchar(255), opisanie varchar(255), ssilka varchar(255), razdel_kod integer, primary key (video_klip_id));
create table lolik_web.video_klip_ocenka (ocenka_id integer not null, video_klip_id integer, primary key (ocenka_id));
create table lolik_web.vopros (vopros_id integer not null auto_increment, tekst varchar(255), opros_id integer, primary key (vopros_id));
create table lolik_web.yazik (yazik_kod varchar(2) not null, opisanie varchar(255), primary key (yazik_kod));
create table lolik_web.znachenie (znachenie_kod integer not null, chislo integer not null, opisanie varchar(255) not null, primary key (znachenie_kod));
alter table lolik_web.albom add index FK5897DB51DF1B685 (razdel_kod), add constraint FK5897DB51DF1B685 foreign key (razdel_kod) references lolik_web.razdel_fotografii (razdel_kod);
alter table lolik_web.fotografia add index FK57027D6CB7C9B96A (albom_id), add constraint FK57027D6CB7C9B96A foreign key (albom_id) references lolik_web.albom (albom_id);
alter table lolik_web.fotografia_ocenka add index FK4D2265C6C58DAC6A (fotografia_id), add constraint FK4D2265C6C58DAC6A foreign key (fotografia_id) references lolik_web.fotografia (fotografia_id);
alter table lolik_web.fotografia_ocenka add index FK4D2265C66A89BF0A (ocenka_id), add constraint FK4D2265C66A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.kompozicia add index FK884ACCE4D226B4CB (muzikalnii_albom_id), add constraint FK884ACCE4D226B4CB foreign key (muzikalnii_albom_id) references lolik_web.muzikalnii_albom (muzikalnii_albom_id);
alter table lolik_web.kompozicia_ocenka add index FKC9403F4E6A89BF0A (ocenka_id), add constraint FKC9403F4E6A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.kompozicia_ocenka add index FKC9403F4E4ADD96A (kompozicia_id), add constraint FKC9403F4E4ADD96A foreign key (kompozicia_id) references lolik_web.kompozicia (kompozicia_id);
alter table lolik_web.lolik_web add index FKA1DFEF40BDBA5AB9 (yazik_kod), add constraint FKA1DFEF40BDBA5AB9 foreign key (yazik_kod) references lolik_web.yazik (yazik_kod);
alter table lolik_web.lolik_web_ocenka add index FKEAECFD72136DC95A (lolik_web_kod), add constraint FKEAECFD72136DC95A foreign key (lolik_web_kod) references lolik_web.lolik_web (lolik_web_kod);
alter table lolik_web.lolik_web_ocenka add index FKEAECFD726A89BF0A (ocenka_id), add constraint FKEAECFD726A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.muzikalnii_albom add index FKEF8DA385B9EE77E (razdel_kod), add constraint FKEF8DA385B9EE77E foreign key (razdel_kod) references lolik_web.razdel_muzika (razdel_kod);
alter table lolik_web.muzikalnii_albom_tranzakcia add index FKC7802BFC5B403CAA (tranzakcia_id), add constraint FKC7802BFC5B403CAA foreign key (tranzakcia_id) references lolik_web.tranzakcia (tranzakcia_id);
alter table lolik_web.muzikalnii_albom_tranzakcia add index FKC7802BFCD226B4CB (muzikalnii_albom_id), add constraint FKC7802BFCD226B4CB foreign key (muzikalnii_albom_id) references lolik_web.muzikalnii_albom (muzikalnii_albom_id);
alter table lolik_web.ocenka add index FKC30C97934AD111BF (znachenie_kod), add constraint FKC30C97934AD111BF foreign key (znachenie_kod) references lolik_web.znachenie (znachenie_kod);
alter table lolik_web.opros add index FK650D455136DC95A (lolik_web_kod), add constraint FK650D455136DC95A foreign key (lolik_web_kod) references lolik_web.lolik_web (lolik_web_kod);
alter table lolik_web.opros_ocenka add index FK9B1926BD55CAB56A (opros_id), add constraint FK9B1926BD55CAB56A foreign key (opros_id) references lolik_web.opros (opros_id);
alter table lolik_web.opros_ocenka add index FK9B1926BD6A89BF0A (ocenka_id), add constraint FK9B1926BD6A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.polzovatel_otvet add index FK45A458AF55CAB56A (opros_id), add constraint FK45A458AF55CAB56A foreign key (opros_id) references lolik_web.opros (opros_id);
alter table lolik_web.polzovatel_otvet_vopros add index FKB552FF2FE8EA4A2D (polzovatel_otvet_id), add constraint FKB552FF2FE8EA4A2D foreign key (polzovatel_otvet_id) references lolik_web.polzovatel_otvet (polzovatel_otvet_id);
alter table lolik_web.polzovatel_otvet_vopros add index FKB552FF2FB08F738A (vopros_id), add constraint FKB552FF2FB08F738A foreign key (vopros_id) references lolik_web.vopros (vopros_id);
alter table lolik_web.razdel add index FKC8185800DC555A74 (tip_razdela_kod), add constraint FKC8185800DC555A74 foreign key (tip_razdela_kod) references lolik_web.tip_razdela (tip_razdela_kod);
alter table lolik_web.razdel add index FKC8185800136DC95A (lolik_web_kod), add constraint FKC8185800136DC95A foreign key (lolik_web_kod) references lolik_web.lolik_web (lolik_web_kod);
alter table lolik_web.razdel_fotografii add index FK61A17B132D9258F1 (razdel_kod), add constraint FK61A17B132D9258F1 foreign key (razdel_kod) references lolik_web.razdel (razdel_kod);
alter table lolik_web.razdel_muzika add index FK366EAB8C2D9258F1 (razdel_kod), add constraint FK366EAB8C2D9258F1 foreign key (razdel_kod) references lolik_web.razdel (razdel_kod);
alter table lolik_web.razdel_ocenka add index FK38D13CB26A89BF0A (ocenka_id), add constraint FK38D13CB26A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.razdel_ocenka add index FK38D13CB22D9258F1 (razdel_kod), add constraint FK38D13CB22D9258F1 foreign key (razdel_kod) references lolik_web.razdel (razdel_kod);
alter table lolik_web.razdel_video add index FK2342CF7C2D9258F1 (razdel_kod), add constraint FK2342CF7C2D9258F1 foreign key (razdel_kod) references lolik_web.razdel (razdel_kod);
alter table lolik_web.tranzakcia add index FKA4B86F022914FE30 (tranzakcia_sostoianie_kod), add constraint FKA4B86F022914FE30 foreign key (tranzakcia_sostoianie_kod) references lolik_web.tranzakcia_sostoianie (tranzakcia_sostoianie_kod);
alter table lolik_web.video_klip add index FK9F8D7F8CFFE4F6EC (razdel_kod), add constraint FK9F8D7F8CFFE4F6EC foreign key (razdel_kod) references lolik_web.razdel_video (razdel_kod);
alter table lolik_web.video_klip_ocenka add index FK20B6BFA660CD07E1 (video_klip_id), add constraint FK20B6BFA660CD07E1 foreign key (video_klip_id) references lolik_web.video_klip (video_klip_id);
alter table lolik_web.video_klip_ocenka add index FK20B6BFA66A89BF0A (ocenka_id), add constraint FK20B6BFA66A89BF0A foreign key (ocenka_id) references lolik_web.ocenka (ocenka_id);
alter table lolik_web.vopros add index FKCFACAD9F55CAB56A (opros_id), add constraint FKCFACAD9F55CAB56A foreign key (opros_id) references lolik_web.opros (opros_id);